### ISSUE TITLE
Add option for blank time per barcode

### ISSUE THREAD

**Issue by T3hUb3rK1tten** [T3hUb3rK1tten/barcOwned#11]
When scanning in auto mode, there is a problem where duplicate characters are "ignored" by most scanners, because the same barcode shows up twice in a row but the barcode itself doesn't change.

I've noticed with my scanners that if there is a short quiet period, i.e. no barcode can be read, they will happily read the same character again. This is a config option on some scanners, called "guard interval" or similar.

We should add an option to the config page for "Inter-barcode delay" or "Blank time per barcode." By default something small like 0.3 seconds will probably be fine and resolve this fairly well.

Alternatively, we could parse through the barcode list and identify duplicates, then subtly change the barcode. For example, Code 128 has several non-printing symbols that might make this work. But that's hacky and might not work for all scanners, it might also mess up the programming barcodes.

**Comment by colin-c** [comment]
Okay, but instead of doing that for every barcode, we could just have the run function look for duplicates and insert the quiet period (configurable) that way we don't needlessly slow down Auto mode since this is only needed for the same code back-to-back, right?
